apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
  labels:
    app: login-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
        - name: login-service
          # ECR 이미지 주소로 수정
          image: 879381276515.dkr.ecr.ap-northeast-2.amazonaws.com/login-service:latest
          # EKS에서는 Always를 권장
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 7010
          env:
            - name: REDIS_HOST_URL
              value: 10.0.1.228
            - name: REDIRECT_URL
              value: a997c41d8abfa42e5adb4f613299f96c-1177132565.ap-northeast-2.elb.amazonaws.com
            - name: DB_MASTER_URL
              value: 10.0.1.228:3306
            - name: DB_SLAVE_URL
              value: 10.0.1.209:3306

