apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
  labels:
    app: login-service

spec:
  replicas: 1  # 필요한 경우 적절히 스케일링
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
        - name: login-service
          # ECR 이미지 주소 (최신 이미지 사용)
          image: 879381276515.dkr.ecr.ap-northeast-2.amazonaws.com/login-service:latest
          # Always로 설정하여 항상 최신 이미지를 가져옴
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                # 종료 전 5초 대기
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 7010  # 애플리케이션 노출 포트
          env:
            # Redis 설정
            - name: REDIS_HOST_URL
              value: redis-service

            # 공용 도메인
            - name: REDIRECT_URL
              value: https://a997c41d8abfa42e5adb4f613299f96c-1177132565.ap-northeast-2.elb.amazonaws.com

            # 데이터베이스 연결 정보
            - name: DB_MASTER_URL
              value: jdbc:mysql://mysql-service:3306/deliveryservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: DB_SLAVE_URL
              value: jdbc:mysql://mysql-service:3306/deliveryservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

            #            - name: DB_SLAVE_NAME
            #              value: replica_user

            # OAuth Redirect URL
            - name: GOOGLE_REDIRECT_URL
              value: https://a997c41d8abfa42e5adb4f613299f96c-1177132565.ap-northeast-2.elb.amazonaws.com/login/oauth2/code/google
            - name: NAVER_REDIRECT_URL
              value: https://a997c41d8abfa42e5adb4f613299f96c-1177132565.ap-northeast-2.elb.amazonaws.com/login/oauth2/code/naver
            - name: KAKAO_REDIRECT_URL
              value: https://a997c41d8abfa42e5adb4f613299f96c-1177132565.ap-northeast-2.elb.amazonaws.com/login/oauth2/code/kakao
