apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
  labels:
    app: login-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
        - name: login-service
          # ECR 이미지 주소로 수정
          image: 879381276515.dkr.ecr.ap-northeast-2.amazonaws.com/login-service:latest
          # EKS에서는 Always를 권장
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 7010
          env:
            - name: REDIS_HOST_URL
              value: 10.0.3.65
            - name: REDIRECT_URL
              value: https://a997c41d8abfa42e5adb4f613299f96c-1177132565.ap-northeast-2.elb.amazonaws.com:80
            - name: DB_MASTER_URL
              value: jdbc:mysql://10.0.3.65:3306/deliveryservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: DB_SLAVE_URL
              value: jdbc:mysql://10.0.3.28:3306/deliveryservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: DB_SLAVE_NAME
              value: replica_user

            - name: GOOGLE_REDIRECT_URL
              value: https://a997c41d8abfa42e5adb4f613299f96c-1177132565.ap-northeast-2.elb.amazonaws.com:80/login/oauth2/code/google
            - name: NAVER_REDIRECT_URL
              value: https://a997c41d8abfa42e5adb4f613299f96c-1177132565.ap-northeast-2.elb.amazonaws.com:80/login/oauth2/code/naver
            - name: KAKAO_REDIRECT_URL
              value: https://a997c41d8abfa42e5adb4f613299f96c-1177132565.ap-northeast-2.elb.amazonaws.com:80/login/oauth2/code/kakao
