name: CI/CD for EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. AWS CLI 인증 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 3. ECR 로그인
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 4. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          IMAGE_URI=879381276515.dkr.ecr.ap-northeast-2.amazonaws.com/my-app:${IMAGE_TAG}
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      # 5. Kubernetes Deployment 업데이트
      - name: Update Kubernetes Deployment
        run: |
          IMAGE_TAG=${{ github.sha }}
          IMAGE_URI=879381276515.dkr.ecr.ap-northeast-2.amazonaws.com/my-app:${IMAGE_TAG}
          kubectl set image deployment/my-app my-app=$IMAGE_URI
